App/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from App import views

urlpatterns = [
    url(r'^index/', views.index, name='home'),
    url(r'^formsearch/', views.formsearch, name='search'),
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^testbs/', views.testbs, name='testbs'),
    url(r'^addform/', views.addform, name='addform'),
    url(r'^getdealform/', views.getdealform, name='getdealform'),
    url(r'^getmyform/', views.getmyform, name='getmyform'),
    url(r'^formdetail/(\d+)/', views.formdetail, name='formdetail'),
    url(r'^formvalid/', views.formvalid, name='formvalid'),
    url(r'^adddealrec/(\d+)/', views.adddealrec),
    url(r'^uploadfile/', views.uploadfile, name='uploadfile'),
    url(r'^formnew/', views.formnew, name='formnew')
]

bootstraplearn/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('App.urls', 'App'), namespace='app')),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-confirm.css' %}">
    {% block ext_css %}

    {% endblock %}
</head>
<body>

{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script language="JavaScript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script language="JavaScript" src="{% static 'js/bootstrap.js' %}"></script>
<script language="JavaScript" src="{% static 'js/jquery-confirm.js' %}"></script>
{% block ext_js %}

{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
{% endblock %}

{% block header %}
    {{ block.super }}

{% endblock %}
{% block content %}
    {{ block.super }}
{% endblock %}

{% block footer %}
    {{ block.super }}
    <footer>
        <nav class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container ">
                <h5 class="text-center text-muted">Copyright.caihan</h5>
                <p class="text-center text-muted">Email:14768454@qq.com</p>
            </div>
        </nav>
    </footer>
{% endblock %}

{% block  ext_js %}

{% endblock %}

templates/form_detail.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/form_detail.css' %}">
{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <h4>工单编号：{{ formdata.id }}
                        <div style="float: right">工单类型：{{ formdata.f_type }}</div>
                    </h4>
                    <div class="text-center">
                        {% if formdata.f_status != '已审批' and formdata.f_status != '已作废' and formdata.f_dealman == user.username %}

                            {% if formdata.f_status == '新建' or formdata.f_status == '已退回' %}
                                <button id="zuofei" class="btn btn-warning" data-toggle="modal" data-target="#myModal">作废</button>
                                <button id="tijiao" class="btn btn-success" data-toggle="modal" data-target="#myModal">提交</button>
                            {% else %}
                                <button id="tuihui" class="btn btn-warning" data-toggle="modal" data-target="#myModal">退回</button>
                                <button id="shenpi" class="btn btn-success" data-toggle="modal" data-target="#myModal">审批</button>
                            {% endif %}
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">工单处理</h4>
                                        </div>
                                        <form action="{% url 'app:formdetail' formdata.id %}" method="post">
                                            {% csrf_token %}
                                            <div class="modal-body">
                                                <textarea class="form-control" id="dealcontent"
                                                          name="dealcontent"
                                                          placeholder="请输入处理意见"
                                                          style="line-height: 16px;height:200px;overflow: auto"
                                                          required="required"></textarea>
                                                <input type="hidden" id="nextstatus" name="nextstatus" value="">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">保存并转派下一环节</button>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        {% endif %}


                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="row ">
                        <div class="col-sm-2 detailtitle">
                            <p>标题</p>
                        </div>
                        <div class="col-sm-10">
                            <p>{{ formdata.f_title }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>提交人</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_createman }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>提交时间</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_createtime|date:"Y-m-d H:i:s" }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>当前处理人</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_dealman }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>当前状态</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_status }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>最后处理人</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_lastdealman }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle">
                            <p>最后处理时间</p>
                        </div>
                        <div class="col-sm-4">
                            <p>{{ formdata.f_lastmodifytime|date:"Y-m-d H:i:s" }}</p>
                        </div>
                        <div class="col-sm-2 detailtitle" style="height: 100px;">
                            <p>工单描述</p>
                        </div>
                        <div class="col-sm-10" style="height: 100px;overflow: auto">
                            <p style="line-height: 16px">{{ formdata.f_content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <h4>附件日志
                        <button id="uploadbtn" class="btn btn-primary">上传文件</button>
                        <input id="fileupload" type="file" name="file" multiple
                               style="display: none;"
                               data-url="{% url 'app:uploadfile' %}"
                               data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}","formid": "{{ formdata.id }}"}'>
                        <span class="small" style="color: red;">只支持txt、word、excel、jpg、png格式，且大小不超过5M</span>
                        <button id="showattachbtn" href="#attachpanel" data-toggle="collapse" style="float: right">
                            <span class="glyphicon glyphicon-menu-down" onclick=""></span></button>
                    </h4>
                </div>
            </div>
            <div id="attachpanel" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="container-fluid" style="border: solid 1px #aaaaaa">
                        <div id="attachments" class="row" style="border: solid 1px #aaaaaa">
                            {% for attachment in attachdata %}
                                <div class="col-sm-2 col-xs-6 detailtitle"><p>上传人</p></div>
                                <div class="col-sm-2 col-xs-6"><p>{{ attachment.uploadman }}</p></div>
                                <div class="col-sm-2 col-xs-6 detailtitle"><p>上传时间</p></div>
                                <div class="col-sm-3 col-xs-6"><p>{{ attachment.uploadtime|date:"Y-m-d H:i:s" }}</p>
                                </div>
                                <div class="col-sm-3 col-xs-12">
                                    <p class="text-center"
                                       style="width: 100%;overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">
                                        <a href="/static/upload{{ attachment.uploadfile.url }}"
                                           download="{{ attachment.filename }}">{{ attachment.filename }}</a>
                                    </p>
                                </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <h4>处理日志
                        <button id="showdealbtn" href="#dealpanel" data-toggle="collapse" style="float: right">
                            <span class="glyphicon glyphicon-menu-down" onclick=""></span></button>
                    </h4>

                </div>
            </div>
            <div id="dealpanel" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="container-fluid" style="border: solid 1px #aaaaaa">
                        {% for dealrec in dealdata %}
                            <div class="row" style="border: solid 1px #aaaaaa">
                                <div class="col-sm-2 col-xs-6 detailtitle"><p>处理人</p></div>
                                <div class="col-sm-2 col-xs-6"><p>{{ dealrec.dealman }}</p></div>
                                <div class="col-sm-2 col-xs-6 detailtitle"><p>操作</p></div>
                                <div class="col-sm-2 col-xs-6"><p>{{ dealrec.operate }}</p></div>
                                <div class="col-sm-2 col-xs-6 detailtitle"><p>处理时间</p></div>
                                <div class="col-sm-2 col-xs-6"><p>{{ dealrec.dealtime|date:"Y-m-d H:i:s" }}</p></div>
                                <div class="col-xs-12"><p style="line-height: 16px">{{ dealrec.dealcontent }}</p></div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block  ext_js %}
    <script src="{% static 'jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'jquery-file-upload/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'jquery-file-upload/jquery.fileupload.js' %}"></script>
    <script type="text/javascript">
        $('#myModal').on('show.bs.modal', function (e) {
            $('#nextstatus').val(e.relatedTarget.id)
        })
        $(function () {
            $('#uploadbtn').click(function () {
                $('#fileupload').click();
            });
            $("#fileupload").fileupload({  //fileupload
                dataType: 'json',
                add: function (e, data) {
                    var uploadErrors = [];
                    //文件大小判断
                    if (data.originalFiles[0].size > (5 * 1024 * 1024)) {
                        uploadErrors.push('请上传不超过5M的文件');
                    }

                    if (uploadErrors.length > 0) {
                        alert(uploadErrors.join("\n"));
                    } else {
                        data.submit();
                    }
                },
                done: function (e, data) {  /* 3. PROCESS THE RESPONSE FROM THE SERVER  这里的data来自于JsonResponse传来的data*/
                    if (data.result.is_valid) {
                        $("#attachments").prepend(
                            "<div class='col-sm-2 col-xs-6 detailtitle'><p>上传人</p></div>" +
                            "<div class='col-sm-2 col-xs-6'><p>" + data.result.uploadman + "</p></div>" +
                            "<div class='col-sm-2 col-xs-6 detailtitle'><p>上传时间</p></div>" +
                            "<div class='col-sm-3 col-xs-6'><p>" + data.result.uploadtime + "</p></div>" +
                            "<div class='col-sm-3 col-xs-12'><p class='text-center'><a href='/static/upload" + data.result.url +
                            "' download='" + data.result.filename + "'>" + data.result.filename + "</a></p></div>"
                        )
                    }
                }
            });
            $('#showdealbtn').click(function () {
                if ($(this).children().hasClass('glyphicon-menu-down')) {
                    $(this).children().removeClass('glyphicon-menu-down')
                    $(this).children().addClass('glyphicon-menu-left')
                } else {
                    $(this).children().removeClass('glyphicon-menu-left')
                    $(this).children().addClass('glyphicon-menu-down')
                }
            });
            $('#showattachbtn').click(function () {
                if ($(this).children().hasClass('glyphicon-menu-down')) {
                    $(this).children().removeClass('glyphicon-menu-down')
                    $(this).children().addClass('glyphicon-menu-left')
                } else {
                    $(this).children().removeClass('glyphicon-menu-left')
                    $(this).children().addClass('glyphicon-menu-down')
                }
            });
        })
    </script>
{% endblock %}

templates/form_new.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/form_new.css' %}">
{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <h4>新建工单
                        <div style="float: right">工单类型：{{ formtypechs }}</div>
                    </h4>
                </div>
            </div>
            <form action="{% url 'app:formnew' %}" method="post">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="container-fluid">

                        <div class="row ">
                            <label for="inputTitle" class="col-sm-2 control-label detailtitle"
                                   style="height: 52px;">标题</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputTitle" name="inputTitle"
                                       placeholder="请输入标题" value="" style="height: 30px" required="required">
                            </div>
                        </div>
                        <div class="row ">
                            <label for="inputTitle" class="col-sm-2 control-label detailtitle"
                                   style="height: 222px;">工单描述</label>

                            <div class="col-sm-10">
                            <textarea class="form-control" id="inputDescrp" name="inputDescrp"
                                      placeholder="请输入工单描述"
                                      style="line-height: 16px;height:200px;overflow: auto"
                                      required="required"></textarea>
                            </div>
                        </div>
                        <input type="hidden" name="formtype" value="{{ formtype }}">

                    </div>
                </div>
                <div class="panel-footer">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary" style="width: 100px">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block  ext_js %}
    <script type="text/javascript">

    </script>
{% endblock %}

templates/index.html
{% extends 'main.html' %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="modal-dialog" style="margin-top: 15%;">
        <div class="modal-content">
            <form action="{% url 'app:login' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header">

                    <h4 class="modal-title text-center" id="myModalLabel">登录</h4>
                </div>
                <div class="modal-body" id="model-body">
                    <div class="form-group">

                        <input type="text" class="form-control" name="username" placeholder="用户名"
                               autocomplete="off">
                    </div>
                    <div class="form-group">

                        <input type="password" class="form-control" name="password" placeholder="密码"
                               autocomplete="off">
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary form-control">登录</button>
                    </div>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
{% endblock %}

{% block footer %}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="modal-dialog" style="margin-top: 15%;">
        <div class="modal-content">
            <form action="{% url 'app:register' %}" method="post" enctype="multipart/form-data" onsubmit="paser_password()">
                {% csrf_token %}
                <div class="modal-header">

                    <h4 class="modal-title text-center" id="myModalLabel">登录</h4>
                </div>
                <div class="modal-body" id="model-body">
                    <div class="form-group">

                        <input type="text" class="form-control" name="username" placeholder="用户名"
                               autocomplete="off">
                    </div>
                    <div class="form-group">

                        <input type="text" class="form-control" name="mobile_number" placeholder="手机号码"
                               autocomplete="off">
                    </div>
                    <div class="form-group">

                        <input type="password" class="form-control" name="password" id="password_input" placeholder="密码"
                               autocomplete="off">
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary form-control">登录</button>
                    </div>

                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
{% endblock %}

{% block footer %}
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jsencrypt.js' %}"></script>
    <script type="text/javascript">
        function paser_password() {
            let password_old = $('#password_input').val()
            let encrypt = new JSEncrypt();
            let public_key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu8ubZLdThmWypavbdD1p\n" +
                "mcgDntGDR3xECQ9LUGis9eXFzGm6/j3rLXTF4NbGUv8MN0PNcOwnREILLOmt/yrH\n" +
                "0fzcF6JkRxFL9COFteJYLf8lvzw0MVBtw/BVemaA4KS8gIekct2ZyvCKuKvYWQ9o\n" +
                "k3zIZCl5IhCsGSVrgffSDMkYNN9x5+lpZkRlZmNLVU1WQ44zg1sz4vQKkw5YsBbC\n" +
                "lwg3m24SVsEKGzQXTEJpTrAejCRG7+goZALaJUCnZHv1dzD5JPGYwIQCJNHcRoGB\n" +
                "MMQ3fYvh7pgi3A2+eX6tVHZv4I07Mg8lBn+RtAEQteKB3TiEzum3tKSOfXzlYUEl\n" +
                "kQIDAQAB";
            encrypt.setPublicKey(public_key);
            let password_new = encrypt.encrypt(password_old);
            $('#password_input').val(password_new)
        }
    </script>
{% endblock %}